using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace grafico
{
    public class Sample : MonoBehaviour
    {
        private DD_DataDiagram m_DataDiagram;
        private GameObject singleLine;

        private mainSerial serialController;

        // Use this for initialization
        void Start()
        {
            GameObject dd = GameObject.Find("DataDiagram");
            if (dd == null)
            {
                Debug.LogWarning("Can't find a game object of DataDiagram");
                return;
            }

            m_DataDiagram = dd.GetComponent<DD_DataDiagram>();
            m_DataDiagram.PreDestroyLineEvent += (s, e) => { singleLine = null; };

            // Encontrar ou criar o objeto que contém o script mainSerial
            serialController = FindObjectOfType<mainSerial>();

            // Iniciar automaticamente a única linha
            StartSingleLine();

            // Iniciar a atualização da temperatura
            StartCoroutine(UpdateLineWithTemperature());
        }

        // Método para iniciar automaticamente a única linha
        void StartSingleLine()
        {
            if (singleLine == null && m_DataDiagram != null)
            {
                // Adicionar uma única linha automaticamente
                singleLine = m_DataDiagram.AddLine("AutoGeneratedLine", Color.blue);
            }
        }

        // Método para atualizar o valor da linha com base na temperatura
        IEnumerator UpdateLineWithTemperature()
        {
            while (true)
            {
                if (serialController != null && singleLine != null)
                {
                    float lastTemperatura = serialController.GetLastTemperatura();
                    m_DataDiagram.InputPoint(singleLine, new Vector2(0.1f, (lastTemperatura)));
                }

                yield return new WaitForSeconds(1f);
            }
        }

        // Update is called once per frame
        void Update()
        {

        }


    }

}